#nullable disable
//Visual Studio Solution to create a Console App, and commit to GitHub. Generated by ChatGPT version gpt-3.5-turbo, Copyright OpenAI.
class DistanceCalculator
{
    static void Main()
    {
        // Input a date
        Console.WriteLine("Enter a date (DD-MM-YYYY): ");
        string inputDate = Console.ReadLine();

        DateTime date;
        if (DateTime.TryParse(inputDate, out date))
        {
            // Get the number of days between the date and a reference date
            TimeSpan timeSpan = date - new DateTime(2000, 1, 1);
            double days = timeSpan.TotalDays;

            // Calculate the distance between Earth and Sun using the average distance (1 AU)
            double distance = CalculateDistance(days);

            Console.WriteLine($"Distance between Earth and Sun on {date.ToString("dd-MM-yyyy")}: {distance} Miles");
        }
        else
        {
            Console.WriteLine("Invalid date format. Please enter a valid date in the format YYYY-MM-DD.");
        }
    }
    static double CalculateDistance(double days)
    {
        // Average distance between Earth and Sun (1 AU)
        double au = 149597870.7; // kilometers

        // Calculate the distance between Earth and Sun
        double distance = au + (0.017 * au) * Math.Sin(2 * Math.PI * days / 365.25);

        return (int)(distance * 0.62137119);
    }
}